// Code generated by MockGen. DO NOT EDIT.
// Source: env.go
//
// Generated by this command:
//
//	mockgen -source=env.go -destination=/Users/gda/Documents/github/qase-tms/qasectl/internal/service/env/mocks/env.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	run "github.com/qase-tms/qasectl/internal/models/run"
	gomock "go.uber.org/mock/gomock"
)

// Mockclient is a mock of client interface.
type Mockclient struct {
	ctrl     *gomock.Controller
	recorder *MockclientMockRecorder
}

// MockclientMockRecorder is the mock recorder for Mockclient.
type MockclientMockRecorder struct {
	mock *Mockclient
}

// NewMockclient creates a new mock instance.
func NewMockclient(ctrl *gomock.Controller) *Mockclient {
	mock := &Mockclient{ctrl: ctrl}
	mock.recorder = &MockclientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockclient) EXPECT() *MockclientMockRecorder {
	return m.recorder
}

// CreateEnvironment mocks base method.
func (m *Mockclient) CreateEnvironment(ctx context.Context, pc, n, d, s, h string) (run.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateEnvironment", ctx, pc, n, d, s, h)
	ret0, _ := ret[0].(run.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateEnvironment indicates an expected call of CreateEnvironment.
func (mr *MockclientMockRecorder) CreateEnvironment(ctx, pc, n, d, s, h any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateEnvironment", reflect.TypeOf((*Mockclient)(nil).CreateEnvironment), ctx, pc, n, d, s, h)
}

// GetEnvironments mocks base method.
func (m *Mockclient) GetEnvironments(ctx context.Context, projectCode string) ([]run.Environment, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetEnvironments", ctx, projectCode)
	ret0, _ := ret[0].([]run.Environment)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetEnvironments indicates an expected call of GetEnvironments.
func (mr *MockclientMockRecorder) GetEnvironments(ctx, projectCode any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetEnvironments", reflect.TypeOf((*Mockclient)(nil).GetEnvironments), ctx, projectCode)
}
