// Code generated by MockGen. DO NOT EDIT.
// Source: milestone.go
//
// Generated by this command:
//
//	mockgen -source=milestone.go -destination=/Users/gda/Documents/github/qase-tms/qasectl/internal/service/milestone/mocks/milestone.go -package=mocks
//

// Package mocks is a generated GoMock package.
package mocks

import (
	context "context"
	reflect "reflect"

	run "github.com/qase-tms/qasectl/internal/models/run"
	gomock "go.uber.org/mock/gomock"
)

// Mockclient is a mock of client interface.
type Mockclient struct {
	ctrl     *gomock.Controller
	recorder *MockclientMockRecorder
}

// MockclientMockRecorder is the mock recorder for Mockclient.
type MockclientMockRecorder struct {
	mock *Mockclient
}

// NewMockclient creates a new mock instance.
func NewMockclient(ctrl *gomock.Controller) *Mockclient {
	mock := &Mockclient{ctrl: ctrl}
	mock.recorder = &MockclientMockRecorder{mock}
	return mock
}

// EXPECT returns an object that allows the caller to indicate expected use.
func (m *Mockclient) EXPECT() *MockclientMockRecorder {
	return m.recorder
}

// CreateMilestone mocks base method.
func (m *Mockclient) CreateMilestone(ctx context.Context, projectCode, n, d, s string, t int64) (run.Milestone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "CreateMilestone", ctx, projectCode, n, d, s, t)
	ret0, _ := ret[0].(run.Milestone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// CreateMilestone indicates an expected call of CreateMilestone.
func (mr *MockclientMockRecorder) CreateMilestone(ctx, projectCode, n, d, s, t any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "CreateMilestone", reflect.TypeOf((*Mockclient)(nil).CreateMilestone), ctx, projectCode, n, d, s, t)
}

// GetMilestones mocks base method.
func (m *Mockclient) GetMilestones(ctx context.Context, projectCode, milestoneName string) ([]run.Milestone, error) {
	m.ctrl.T.Helper()
	ret := m.ctrl.Call(m, "GetMilestones", ctx, projectCode, milestoneName)
	ret0, _ := ret[0].([]run.Milestone)
	ret1, _ := ret[1].(error)
	return ret0, ret1
}

// GetMilestones indicates an expected call of GetMilestones.
func (mr *MockclientMockRecorder) GetMilestones(ctx, projectCode, milestoneName any) *gomock.Call {
	mr.mock.ctrl.T.Helper()
	return mr.mock.ctrl.RecordCallWithMethodType(mr.mock, "GetMilestones", reflect.TypeOf((*Mockclient)(nil).GetMilestones), ctx, projectCode, milestoneName)
}
